# Generated by Django 5.0.1 on 2024-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodleID", models.IntegerField()),
                ("productID", models.IntegerField()),
                ("orderID", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
