# Generated by Django 5.0.1 on 2024-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="productID",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
