# Generated by Django 5.0.1 on 2024-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminApprovalFeedback",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
            ],
            options={
                "db_table": "admin_approval_feedback",
            },
        ),
    ]
