# Generated by Django 5.0.1 on 2024-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_actions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminApprovalFeedbackResource",
            fields=[
                ("resource_id", models.IntegerField(primary_key=True, serialize=False)),
                ("feedback", models.TextField()),
            ],
            options={
                "db_table": "admin_approval_feedback_resources",
            },
        ),
    ]
