# Generated by Django 5.0.1 on 2024-02-11 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="passphrase",
            new_name="password",
        ),
    ]
