# Generated by Django 5.0.1 on 2024-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_rename_passphrase_student_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="collegeStudent",
            fields=[
                ("moodleID", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
            ],
            options={
                "db_table": "college_students",
            },
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
