# Generated by Django 5.0.1 on 2024-03-25 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_studentmetainfo"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="studentmetainfo",
            table="user_information",
        ),
    ]
