# Generated by Django 5.0.1 on 2024-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prouduct_listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodleID", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("selected_year", models.CharField(max_length=255)),
                ("selected_branch", models.CharField(max_length=255)),
                ("selected_item_type", models.TextField()),
                ("selected_condition", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("image_urls", models.TextField()),
            ],
        ),
    ]
