# Generated by Django 5.0.1 on 2024-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_prouduct_listing_admin_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="prouduct_listing",
            name="listing_published",
            field=models.CharField(default="false", max_length=5),
            preserve_default=False,
        ),
    ]
