# Generated by Django 5.0.1 on 2024-03-22 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_prouduct_listing_listing_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prouduct_listing",
            name="listing_published",
        ),
    ]
