# Generated by Django 5.0.1 on 2024-03-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_rename_prouduct_listing_productlisting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodleID", models.IntegerField()),
                ("resource", models.TextField()),
            ],
            options={
                "db_table": "resource_listings",
            },
        ),
    ]
