# Generated by Django 5.0.1 on 2024-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_resourcelisting_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarredResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodleID", models.IntegerField()),
                ("resourceID", models.IntegerField()),
            ],
            options={
                "db_table": "starred_resources",
            },
        ),
    ]
